<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $now = Carbon::now();
        // Track 1
        // Hero 1 - Track 2
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1021,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Câu 1',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 1,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1022,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Câu 2',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 2,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1023,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-3',
                                                   'title'       => 'Câu 3',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 3,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1026,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Câu 1',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 6,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1027,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Câu 2',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 7,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1028,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-3',
                                                   'title'       => 'Câu 3',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 8,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1029,
                                                   'track_id'    => 102,
                                                   'slug'        => 'question-4',
                                                   'title'       => 'Câu 4',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 9,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        //Hero 1 - Track 3
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1031,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Câu 1',
                                                   'group'       => 'Finance',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 1,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1032,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Câu 2',
                                                   'group'       => 'Finance',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 2,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1033,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question',
                                                   'title'       => 'Câu hỏi',
                                                   'group'       => 'Legal',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 3,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1034,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Câu hỏi 1',
                                                   'group'       => 'PACS',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 4,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1035,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Câu hỏi 2',
                                                   'group'       => 'PACS',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 5,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 1036,
                                                   'track_id'    => 103,
                                                   'slug'        => 'question',
                                                   'title'       => 'Câu hỏi',
                                                   'group'       => 'People',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 6,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        //Hero 2 - track 1
        //Hero 2 - track 2
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2021,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Câu hỏi 1',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 1,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2022,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Câu hỏi 2',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 2,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2023,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-3',
                                                   'title'       => 'Câu hỏi 3',
                                                   'group'       => 'Distributing',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 3,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        // selling
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2026,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Thử thách xếp tủ lạnh',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 6,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2027,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Thử thách xếp tủ lạnh (tiếp)',
                                                   'group'       => 'Selling',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 7,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2028,
                                                   'track_id'    => 202,
                                                   'slug'        => 'question-3',
                                                   'title'       => 'Question 3',
                                                   'group'       => 'Selling',
                                                   'description' => 'Từ các options của tệp khách hàng, và kênh phân phối có sẵn (để ở bên dưới), người chơi kéo thả các options về đúng chỗ của 4 khách hàng trên background.',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 8,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        //Hero 2 - track 3
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2031,
                                                   'track_id'    => 203,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Question 1',
                                                   'group'       => 'Finance',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 1,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2032,
                                                   'track_id'    => 203,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Question 2',
                                                   'group'       => 'Finance',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 2,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2033,
                                                   'track_id'    => 203,
                                                   'slug'        => 'question-1',
                                                   'title'       => 'Question 1',
                                                   'group'       => 'IT',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 3,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2034,
                                                   'track_id'    => 203,
                                                   'slug'        => 'question-2',
                                                   'title'       => 'Question 2',
                                                   'group'       => 'IT',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 4,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2035,
                                                   'track_id'    => 203,
                                                   'slug'        => 'error-1',
                                                   'title'       => 'Error 1',
                                                   'group'       => 'IT',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 5,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2036,
                                                   'track_id'    => 203,
                                                   'slug'        => 'error-2',
                                                   'title'       => 'Error 2',
                                                   'group'       => 'IT',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 6,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2037,
                                                   'track_id'    => 203,
                                                   'slug'        => 'ki-nang-1',
                                                   'title'       => 'Kĩ năng 1',
                                                   'group'       => 'People',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 7,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2038,
                                                   'track_id'    => 203,
                                                   'slug'        => 'ki-nang-2',
                                                   'title'       => 'Kĩ năng 2',
                                                   'group'       => 'People',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 8,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2039,
                                                   'track_id'    => 203,
                                                   'slug'        => 'ki-nang-3',
                                                   'title'       => 'Kĩ năng 3',
                                                   'group'       => 'People',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 9,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
        DB::table('questions')->insertOrIgnore([
                                                   'id'          => 2040,
                                                   'track_id'    => 203,
                                                   'slug'        => 'ki-nang-4',
                                                   'title'       => 'Kĩ năng 4',
                                                   'group'       => 'People',
                                                   'description' => '',
                                                   'infer'       => '',
                                                   'explain'     => '',
                                                   'template'    => '',
                                                   'order'       => 10,
                                                   'created_at'  => $now,
                                                   'updated_at'  => $now,
                                               ]);
    }
}
